config/routes.rb
Rails.application.routes.draw do

  root 'pages#main'
  post 'equation' => 'api#solve'
  
  get 'login' => 'pages#login_page'
  get 'registration' => 'pages#registration_page'
  
  post 'login_api' => 'api#login'
  post 'registration_api' => 'api#registration'
  
  

end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def login
    username = params[:user][:username]
    password = params[:user][:password]
    
    response = send_api('login',{ username: username, password: password}.to_json)

    check_response(response)
    redirect_after_authorization(response)
  end
    
  def registration
    username = params[:user][:username]
    password = params[:user][:password]
    password_confirmation = params[:user][:password_confirmation]
    
    response = send_api('registration',{ username: username, password: password, password_confirmation: password_confirmation}.to_json)
    
    check_response(response)
    redirect_after_authorization(response)
  end
    
    
  def solve
    response = send_api('solve',params[:equation].to_json)
    check_response(response)
    data = response.body
    
    if data['errors']
      @answer = "Not the correct format of the equation"
      flash.now[:notice] = JSON.parse(data)['errors']
    else
      @answer = data 
    end
  end
  
  
  private
  
  
  def send_api(url,data)
    call_api = SendApi.new(url,data,cookies[:token])
    call_api.send    
  end
  
  def check_response(response)
    case response.code
    when 200
      puts "Log: The request was successful"
    when 401
      raise Errors::NotAuthorized
    else
      raise Errors::ApiError
    end    
  end

  def redirect_after_authorization(response)
    data = JSON.parse(response.body)
    flash[:notice]  = data['message']
    cookies[:token] = data['token']
    redirect_to root_path 
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from Errors::NotAuthorized, :with => :user_not_authorized
  rescue_from Errors::ApiError, :with => :api_error

  private

  def user_not_authorized
    flash[:error] = "You don't authorized!"
    redirect_to :back
  end

  def api_error
    flash[:error] = "Server error!"
    redirect_to :back
  end
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end
  
  def login_page
  end
  
  def registration_page
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="iCard" class="col-md-offset-4 col-md-4 col-sm-offset-2 col-sm-8 col-xs-12">
    <div class="container-fluid text-center">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/login_page.slim
div class="col-md-3"
  = link_to '<< Back', root_path
div class="col-md-3 col-md-offset-6"
  = link_to 'Registration', registration_path
hr
h2 Login

#errors
  = render partial: "shared/flash_errors", flash: flash  
    
= simple_form_for :user, url: login_api_path, :defaults => {:required => false} do |f| 
  = f.input :username, label: 'Username'
  = f.input :password, label: 'Password'
  = f.button :submit, "Login!", data: { disable_with: "Wait, please..."}

app/views/pages/main.slim
div class="col-md-3"
  = link_to 'Login', login_path
div class="col-md-3 col-md-offset-6"
  = link_to 'Registration', registration_path
hr
h2 System for solving mathematical equations
h3 Only linear and quadratic equations 
#errors
  = render partial: "shared/flash_errors", flash: flash  
    
= simple_form_for :equation, remote: true, url: equation_path, :defaults => {:required => false} do |f| 
  = f.input :type, collection: ["linear","quadratic"], id:"equation_select", label: 'Type:', prompt: "Select type of equation", selected: "linear"
  = f.input :equation_text, label: 'Equation', hint: 'Example: x + 5x = 12 , x^2+3x-3=-x^2-2x'
  = f.button :submit, "Solve equation!", data: { disable_with: "Wait, please..."}

#answer class="text-center"

app/views/pages/registration_page.slim
div class="col-md-3"
  = link_to '<< Back', root_path
div class="col-md-3 col-md-offset-6"
  = link_to 'Login', login_path
hr
h2 Registration

#errors
  = render partial: "shared/flash_errors", flash: flash  
    
= simple_form_for :user, url: registration_api_path, :defaults => {:required => false} do |f| 
  = f.input :username, label: 'Username'
  = f.input :password, label: 'Password'
  = f.input :password_confirmation, label: 'Password confirmation'
  = f.button :submit, "Registration!", data: { disable_with: "Wait, please..."}

app/views/shared/_flash_errors.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-info">
    <%= value %>
  </div>
<% end %>